#!/usr/bin/env tsx
/**
 * 엑셀 파일에서 테스트 메타데이터를 가져오는 스크립트
 * 사용법: npm run import:tests -- --file=tests.xlsx
 */
import { readFileSync, writeFileSync } from "fs";
import { read, utils } from "xlsx";
import type { TestMeta } from "../src/types";

function main() {
  const args = process.argv.slice(2);
  const fileArg = args.find((a) => a.startsWith("--file="));
  if (!fileArg) {
    console.error("사용법: npm run import:tests -- --file=<파일경로.xlsx>");
    process.exit(1);
  }

  const filePath = fileArg.replace("--file=", "");
  const buffer = readFileSync(filePath);
  const wb = read(buffer);
  const sheet = wb.Sheets[wb.SheetNames[0]];
  const rows = utils.sheet_to_json<Record<string, string>>(sheet);

  console.log(`📊 ${rows.length}개 행을 읽었습니다.`);

  const tests: TestMeta[] = rows
    .filter((row) => row.id && row.slug && row.title)
    .map((row, i) => ({
      id: row.id || `import-${i + 1}`,
      slug: row.slug,
      title: row.title,
      categorySlug: row.categorySlug || "jonghap-seonghyang",
      hook: row.hook || row.title,
      description: row.description || "",
      target: row.target || "누구나",
      estimatedMinutes: Number(row.estimatedMinutes) || 3,
      questionCount: Number(row.questionCount) || 12,
      resultCount: Number(row.resultCount) || 8,
      adFriendlyScore: Number(row.adFriendlyScore) || 0.7,
      viralScore: Number(row.viralScore) || 0.7,
      priority: Number(row.priority) || 50,
      tags: row.tags ? row.tags.split(",").map((t) => t.trim()) : [],
      isFeatured: row.isFeatured === "true",
      isNew: row.isNew === "true",
      status: (row.status as TestMeta["status"]) || "generated",
    }));

  const output = `// AUTO-GENERATED by scripts/import-tests.ts
// ${new Date().toISOString()}
import type { TestMeta } from "../../types";

export const importedTests: TestMeta[] = ${JSON.stringify(tests, null, 2)};
`;

  const outputPath = "src/data/generated/importedTests.generated.ts";
  writeFileSync(outputPath, output, "utf-8");
  console.log(`✅ ${tests.length}개 테스트를 ${outputPath}에 저장했습니다.`);
}

main();
